server:
  port: 8080

jira:
  base-url: https://jiraeu.epam.com
  api-token: YOUR_JIRA_API_TOKEN
  project: EPMCDMETST
  subject: YOUR_JIRA_SUBJECT

dial:
  endpoint: https://ai-proxy.lab.epam.com/openai/deployments
  foundation-model: o3-mini-2025-01-31
  api-key: YOUR_DIAL_API_KEY 